# Generated by Django 4.2.11 on 2024-04-24 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Debt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DcID', models.CharField(max_length=255)),
                ('UserName', models.CharField(max_length=255)),
                ('Record', models.CharField(max_length=255)),
                ('Account', models.CharField(max_length=255)),
                ('PokerID', models.CharField(max_length=255)),
                ('PokerID2', models.CharField(max_length=255)),
                ('Total', models.FloatField(default=0.0)),
            ],
        ),
    ]
