# Generated by Django 4.2.11 on 2024-05-01 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DebtTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debtors', models.CharField(max_length=255)),
                ('creditors', models.CharField(max_length=255)),
                ('amount', models.FloatField(default=0.0)),
            ],
        ),
    ]
