# Generated by Django 4.2.11 on 2024-05-02 15:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_delete_debttransaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='debt',
            name='PokerID2',
        ),
        migrations.AddField(
            model_name='debt',
            name='WOL',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='debt',
            name='clear',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='debt',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
