# Generated by Django 4.2.11 on 2024-05-04 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_debt_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='debt',
            name='clear',
        ),
    ]
